
    create table item_pedido (
       desconto float8,
        preco float8,
        quantidade int4,
        produto_id int4 not null,
        pedido_id int4 not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id int4 not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas int4,
        pedido_id int4 not null,
        primary key (pedido_id)
    );

    create table produto_categoria (
       produto_id int4 not null,
        categoria_id int4 not null
    );

    create table tb_categoria (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_cidade (
       id int4 generated by default as identity,
        nome varchar(255),
        estado_id int4,
        primary key (id)
    );

    create table tb_cliente (
       id int4 generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo int4,
        primary key (id)
    );

    create table tb_endereco (
       id int4 generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id int4,
        cliente_id int4,
        primary key (id)
    );

    create table tb_estado (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_pagamento (
       pedido_id int4 not null,
        estado int4,
        primary key (pedido_id)
    );

    create table tb_pedido (
       id int4 generated by default as identity,
        instante timestamp,
        cliente_id int4,
        endereco_de_entrega_id int4,
        primary key (id)
    );

    create table tb_produto (
       id int4 generated by default as identity,
        nome varchar(255),
        preco float8,
        primary key (id)
    );

    create table telefone (
       cliente_id int4 not null,
        telefones varchar(255)
    );

    alter table if exists tb_cliente 
       add constraint UK_ir2m70agseiyyajtaxq7wsw20 unique (email);

    alter table if exists item_pedido 
       add constraint FKr4yg1jcjs9u1n3e9xo8dc2g3j 
       foreign key (produto_id) 
       references tb_produto;

    alter table if exists item_pedido 
       add constraint FK3b4n94fwwjnjgun366d6pvaoa 
       foreign key (pedido_id) 
       references tb_pedido;

    alter table if exists pagamento_com_boleto 
       add constraint FKh0mdd85itayupulhqtfvx2hpc 
       foreign key (pedido_id) 
       references tb_pagamento;

    alter table if exists pagamento_com_cartao 
       add constraint FK7cnus10j1wx9bfc58jknoefv4 
       foreign key (pedido_id) 
       references tb_pagamento;

    alter table if exists produto_categoria 
       add constraint FKms3o1ji6o60h9s4acjqqc5fw5 
       foreign key (categoria_id) 
       references tb_categoria;

    alter table if exists produto_categoria 
       add constraint FKb5u1xuiroy0tls0b2odm8aj64 
       foreign key (produto_id) 
       references tb_produto;

    alter table if exists tb_cidade 
       add constraint FKlxge3ne91xrep1oe4cvrjldmm 
       foreign key (estado_id) 
       references tb_estado;

    alter table if exists tb_endereco 
       add constraint FKotpdj815kf867dbkfbctglsjj 
       foreign key (cidade_id) 
       references tb_cidade;

    alter table if exists tb_endereco 
       add constraint FKtqe8u5ggrtf93dr80hiibdfd 
       foreign key (cliente_id) 
       references tb_cliente;

    alter table if exists tb_pagamento 
       add constraint FKjghfnncmma1w9wn5hnpq6nhx2 
       foreign key (pedido_id) 
       references tb_pedido;

    alter table if exists tb_pedido 
       add constraint FKajo6v90obpung9h40lcain479 
       foreign key (cliente_id) 
       references tb_cliente;

    alter table if exists tb_pedido 
       add constraint FKmfmrxaiieg7pbiuii68005j3q 
       foreign key (endereco_de_entrega_id) 
       references tb_endereco;

    alter table if exists telefone 
       add constraint FK9s2f0m9acerx7vax5kgq7akk3 
       foreign key (cliente_id) 
       references tb_cliente;

    create table item_pedido (
       desconto float8,
        preco float8,
        quantidade int4,
        produto_id int4 not null,
        pedido_id int4 not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id int4 not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas int4,
        pedido_id int4 not null,
        primary key (pedido_id)
    );

    create table produto_categoria (
       produto_id int4 not null,
        categoria_id int4 not null
    );

    create table tb_categoria (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_cidade (
       id int4 generated by default as identity,
        nome varchar(255),
        estado_id int4,
        primary key (id)
    );

    create table tb_cliente (
       id int4 generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo int4,
        primary key (id)
    );

    create table tb_endereco (
       id int4 generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id int4,
        cliente_id int4,
        primary key (id)
    );

    create table tb_estado (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_pagamento (
       pedido_id int4 not null,
        estado int4,
        primary key (pedido_id)
    );

    create table tb_pedido (
       id int4 generated by default as identity,
        instante timestamp,
        cliente_id int4,
        endereco_de_entrega_id int4,
        primary key (id)
    );

    create table tb_produto (
       id int4 generated by default as identity,
        nome varchar(255),
        preco float8,
        primary key (id)
    );

    create table telefone (
       cliente_id int4 not null,
        telefones varchar(255)
    );

    alter table if exists tb_cliente 
       add constraint UK_ir2m70agseiyyajtaxq7wsw20 unique (email);

    alter table if exists item_pedido 
       add constraint FKr4yg1jcjs9u1n3e9xo8dc2g3j 
       foreign key (produto_id) 
       references tb_produto;

    alter table if exists item_pedido 
       add constraint FK3b4n94fwwjnjgun366d6pvaoa 
       foreign key (pedido_id) 
       references tb_pedido;

    alter table if exists pagamento_com_boleto 
       add constraint FKh0mdd85itayupulhqtfvx2hpc 
       foreign key (pedido_id) 
       references tb_pagamento;

    alter table if exists pagamento_com_cartao 
       add constraint FK7cnus10j1wx9bfc58jknoefv4 
       foreign key (pedido_id) 
       references tb_pagamento;

    alter table if exists produto_categoria 
       add constraint FKms3o1ji6o60h9s4acjqqc5fw5 
       foreign key (categoria_id) 
       references tb_categoria;

    alter table if exists produto_categoria 
       add constraint FKb5u1xuiroy0tls0b2odm8aj64 
       foreign key (produto_id) 
       references tb_produto;

    alter table if exists tb_cidade 
       add constraint FKlxge3ne91xrep1oe4cvrjldmm 
       foreign key (estado_id) 
       references tb_estado;

    alter table if exists tb_endereco 
       add constraint FKotpdj815kf867dbkfbctglsjj 
       foreign key (cidade_id) 
       references tb_cidade;

    alter table if exists tb_endereco 
       add constraint FKtqe8u5ggrtf93dr80hiibdfd 
       foreign key (cliente_id) 
       references tb_cliente;

    alter table if exists tb_pagamento 
       add constraint FKjghfnncmma1w9wn5hnpq6nhx2 
       foreign key (pedido_id) 
       references tb_pedido;

    alter table if exists tb_pedido 
       add constraint FKajo6v90obpung9h40lcain479 
       foreign key (cliente_id) 
       references tb_cliente;

    alter table if exists tb_pedido 
       add constraint FKmfmrxaiieg7pbiuii68005j3q 
       foreign key (endereco_de_entrega_id) 
       references tb_endereco;

    alter table if exists telefone 
       add constraint FK9s2f0m9acerx7vax5kgq7akk3 
       foreign key (cliente_id) 
       references tb_cliente;

    create table item_pedido (
       desconto float8,
        preco float8,
        quantidade int4,
        produto_id int4 not null,
        pedido_id int4 not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id int4 not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas int4,
        pedido_id int4 not null,
        primary key (pedido_id)
    );

    create table produto_categoria (
       produto_id int4 not null,
        categoria_id int4 not null
    );

    create table tb_categoria (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_cidade (
       id int4 generated by default as identity,
        nome varchar(255),
        estado_id int4,
        primary key (id)
    );

    create table tb_cliente (
       id int4 generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo int4,
        primary key (id)
    );

    create table tb_endereco (
       id int4 generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id int4,
        cliente_id int4,
        primary key (id)
    );

    create table tb_estado (
       id int4 generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_pagamento (
       pedido_id int4 not null,
        estado int4,
        primary key (pedido_id)
    );

    create table tb_pedido (
       id int4 generated by default as identity,
        instante timestamp,
        cliente_id int4,
        endereco_de_entrega_id int4,
        primary key (id)
    );

    create table tb_produto (
       id int4 generated by default as identity,
        nome varchar(255),
        preco float8,
        primary key (id)
    );

    create table telefone (
       cliente_id int4 not null,
        telefones varchar(255)
    );

    alter table if exists tb_cliente 
       add constraint UK_ir2m70agseiyyajtaxq7wsw20 unique (email);

    alter table if exists item_pedido 
       add constraint FKr4yg1jcjs9u1n3e9xo8dc2g3j 
       foreign key (produto_id) 
       references tb_produto;

    alter table if exists item_pedido 
       add constraint FK3b4n94fwwjnjgun366d6pvaoa 
       foreign key (pedido_id) 
       references tb_pedido;

    alter table if exists pagamento_com_boleto 
       add constraint FKh0mdd85itayupulhqtfvx2hpc 
       foreign key (pedido_id) 
       references tb_pagamento;

    alter table if exists pagamento_com_cartao 
       add constraint FK7cnus10j1wx9bfc58jknoefv4 
       foreign key (pedido_id) 
       references tb_pagamento;

    alter table if exists produto_categoria 
       add constraint FKms3o1ji6o60h9s4acjqqc5fw5 
       foreign key (categoria_id) 
       references tb_categoria;

    alter table if exists produto_categoria 
       add constraint FKb5u1xuiroy0tls0b2odm8aj64 
       foreign key (produto_id) 
       references tb_produto;

    alter table if exists tb_cidade 
       add constraint FKlxge3ne91xrep1oe4cvrjldmm 
       foreign key (estado_id) 
       references tb_estado;

    alter table if exists tb_endereco 
       add constraint FKotpdj815kf867dbkfbctglsjj 
       foreign key (cidade_id) 
       references tb_cidade;

    alter table if exists tb_endereco 
       add constraint FKtqe8u5ggrtf93dr80hiibdfd 
       foreign key (cliente_id) 
       references tb_cliente;

    alter table if exists tb_pagamento 
       add constraint FKjghfnncmma1w9wn5hnpq6nhx2 
       foreign key (pedido_id) 
       references tb_pedido;

    alter table if exists tb_pedido 
       add constraint FKajo6v90obpung9h40lcain479 
       foreign key (cliente_id) 
       references tb_cliente;

    alter table if exists tb_pedido 
       add constraint FKmfmrxaiieg7pbiuii68005j3q 
       foreign key (endereco_de_entrega_id) 
       references tb_endereco;

    alter table if exists telefone 
       add constraint FK9s2f0m9acerx7vax5kgq7akk3 
       foreign key (cliente_id) 
       references tb_cliente;
